#!/usr/bin/perl -w

# perl -Iblib/lib misc/process_variable_length 50aacc134d422470455310
# will dump the full decode for that message

use strict;
use xPL::RF;
my $rf = xPL::RF->new(source => "bnz-rftest.default", verbose => 0);
foreach (@ARGV) {
  print $_, "\n\n";
  my $r = $rf->process_variable_length(pack "H*", $_);
  if ($r) {
    print $r->{length}," bytes\n\n";
    if ($r->{messages} && @{$r->{messages}}) {
      print scalar @{$r->{messages}}, " messages\n\n";
      foreach my $m (@{$r->{messages}}) {
        print $m->string();
      }
      print "\n";
    } else {
      print "0 messages\n\nempty\n\n";
    }
  } else {
    print "undef\n\nundef\n\n";
  }
}
