#!/bin/sh
# Copyright (C) 2007 by Mark Hindess
/bin/cat <<EOF
xl0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        options=1<RXCSUM>
        inet 192.168.3.13 netmask 0xffffff00 broadcast 192.168.3.255
        inet6 fe80::201:2ff:fe30:3663%xl0 prefixlen 64 scopeid 0x1
        ether 00:01:02:30:36:63
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
EOF
